Feature emotions textarea
p-foundation/pink-app pull request #17
Opened 2024-02-05 19:12 UTC by ElenaPodv

## Description

_Please provide a concise description of the changes introduced by this pull request._

## Changes Made

_List the specific changes made in this pull request._

## Screenshots or GIFs (if applicable)

_If your changes include visual modifications or improvements, consider attaching screenshots or GIFs to showcase them._

## Checklist

Before submitting this pull request, please ensure the following:

- [ ] I've validated my HTML with [Nu Html Checker](https://validator.w3.org/nu/), and it outputs no errors
- [ ] I've checked my HTML with [HTML Tree Generator](https://yoksel.github.io/html-tree/en/), and it outputs no errors
- I've ensured that the layout matches the mockup for the following control points:
  - [ ] 1200px
  - [ ] 660px
  - [ ] 320px

2024-02-06 18:44 UTC, MarPostovik commented
@ElenaPodv  You did an excellent job laying out the textarea UI element! I have left a few suggestions and comments for improvements.
Please request another code review once you have addressed my comments.
Feel free to reach out if you have any questions or doubts.

2024-02-07 07:29 UTC, ElenaPodv commented on blocks/textarea/textarea.css
> +  overflow: hidden;
Done

2024-02-07 07:42 UTC, ElenaPodv commented on blocks/textarea/textarea.css
> +.textarea:focus {
Done

2024-02-07 07:42 UTC, ElenaPodv commented on blocks/textarea/textarea.css
> +  line-height: 30px;
Done

2024-02-07 07:42 UTC, ElenaPodv commented on blocks/textarea/textarea.css
> +  font-weight: 400;
Done

2024-02-07 07:42 UTC, ElenaPodv commented on blocks/textarea/textarea.css
> +  font-family: "Open Sans", sans-serif;
Done

2024-02-07 08:17 UTC, ElenaPodv commented on blocks/textarea/textarea.css
> +.textarea {
Done

2024-02-08 13:58 UTC, MarPostovik requested changes

2024-02-08 13:58 UTC, MarPostovik commented on blocks/textarea/textarea.css
> +  line-height: 166.667%;
It is better to set line-height in fractional numbers instead of percentages. In your case, it will look like this:
`line-height: 1.66;`

2024-02-08 13:58 UTC, MarPostovik commented on blocks/textarea/textarea.css
> +.form__textarea::placeholder {
You have written styles for placeholder in `form__textarea`, but there is no textarea with this class name. Please, change it to
```
 .textarea::placeholder {
  Rest of your code
 }
```

2024-02-16 15:25 UTC, naumch1k approved these changes
@ElenaPodv, congratulations on your approved pull request! 🥳 🥳 🥳 Your code will soon be merged into the main branch.
A big thank you to @MarPostovik  for her thorough code review 🙏 You both did an excellent job ❤️

Just a friendly reminder:
On your local machine, switch to the main branch and delete the `feature-emotions-textarea` branch.

```bash
git checkout main 
git branch -D feature-emotions-textarea 
```

Also, before creating a new branch for your next feature, always remember to execute the `git pull` command to fetch the latest updates from the GitHub repository. This ensures that your new branch is based on the most recent version of the code.

Keep up the great work!

2024-02-16 15:28 UTC, merged