This pull request resolves [#31](https://github.com/p-foundation/pink-app/issues/31)
p-foundation/pink-app pull request #39
Opened 2024-04-08 09:07 UTC by rasokolovska

## Description of the problem

> The project faced a problem with a color-changing link to the main page that leads nowhere. When you hover or hold down the cursor on this link, it changes color, which can lead to user confusion and gives the impression that the link has the functionality to go to another page, although it does not.

## Solution to the problem
The following changes were made to resolve this issue:

> Checked out updates from the main branch using the git pull command.

> Created a new branch named `fix-hover-on-inactive-link`

> Changes have been made to the `header__navigation-link.css` file, which uses the CSS `:not()` pseudo-class to exclude the` header__navigation-link_active` state in the hovered and active link states:
```html
.header__navigation-link:not(.header__navigation-link_active):hover{
   color: rgb(178, 40, 102);
}
```
```html
.header__navigation-link:not(.header__navigation-link_active):active{
    color: rgb(255, 255, 255, 0.5);
}
```
We tested the changes on a real server to confirm that the link to the main page does not respond to hovering and active state.

2024-04-08 21:07 UTC, naumch1k requested changes
Hey, @rasokolovska Your changes look good! But before we merge your branch into the main, we need to do a **rebase**. Here's the situation: since you branched off, the main branch has been updated with pull request #42.

In the fourth line of the file `header__navigation-link.css`, Diana used newly created CSS variable `--common-transition`. However, in your version, it still uses `all 0.5s ease`.

To avoid accidentally overriding Diana's changes, we'll perform a rebase.
1. In VSCode, ensure you're in the `fix-hover-on-inactive-link` branch.
2. In the terminal, run the command `git rebase main`. There shouldn't be any conflicts, and you should see a message indicating a successful rebase: 
<img width="542" alt="Screenshot 2024-04-08 at 4 01 25 PM" src="https://github.com/p-foundation/pink-app/assets/76534205/20900451-acb2-4dc0-88ae-5c219c4e5ec8">

**What just happened?** Note that Diana's commits have been added to the commit history, and your commit is now on top of hers. You can view the commit history in the terminal by using the command `git log --oneline`:
<img width="1049" alt="Screenshot 2024-04-08 at 3 48 47 PM" src="https://github.com/p-foundation/pink-app/assets/76534205/55a202cb-db60-48a1-87ea-ee71d61a0a20">

Compare it with the commit history in your branch:
<img width="1058" alt="Screenshot 2024-04-08 at 3 51 06 PM" src="https://github.com/p-foundation/pink-app/assets/76534205/61879ebd-a313-4412-93e1-322168adf0e4">

You can also check out `header__navigation-link.css` again and see that line 4 is updated to use the CSS variable `--common-transition`.

3. Sync your local and remote repositories using the command `git push -f`.

@NazarPauk @MarPostovik I suggest you guys do it together 😉 Let me know if you have any questions

2024-04-08 21:29 UTC, naumch1k commented
@rasokolovska Also, could you make these formatting changes to the PR description?

1. Please avoid formatting texts as quotes unless they're actual quotations. It makes the text a bit harder to read. Plus, when we check these elements in developer tools (see screenshot), we notice that even in the HTML markup of this page, your texts are wrapped in blockquote. It's not ideal and makes the GitHub page less accessible.
 
<img width="1277" alt="Screenshot 2024-04-08 at 4 09 08 PM" src="https://github.com/p-foundation/pink-app/assets/76534205/aa56ddd4-fe12-48a0-9081-5cdf49fd649b">

2. Could you also remove the following from the **Solution to the problem** section: 
- Checked out updates from the main branch using the git pull command.
- Created a new branch named `fix-hover-on-inactive-link`.

Please use this part of your PR description to list the actual changes you made to the codebase 😉

3. And lastly, could you switch `html` to `CSS` in code blocks to apply inline formatting? (see video below for reference):

https://github.com/p-foundation/pink-app/assets/76534205/3c1698db-00d0-4ac6-81b4-c82e6450c305

2024-04-10 07:00 UTC, rasokolovska commented
Hi, thanks for the feedback, I have made changes and corrections

2024-04-10 14:09 UTC, naumch1k approved these changes
@rasokolovska Your pull request has been approved. Great job!

2024-04-10 14:09 UTC, merged